spring:
  application:
    name: homepage
  web:
    resources:
      static-locations: classpath:/static/,file:${app.public-data-root}/
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB
  datasource:
    url: jdbc:mysql://localhost:3306/healthiermo?useSSL=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  security:
    user:
      name: ${ADMIN_USER_NAME}
      password: ${ADMIN_USER_HASHED_PASSWORD}
server:
  port: 80
  tomcat:
    max-swallow-size: -1

app:
  public-data-root: ./.data
  audio-files:
    path: ${app.public-data-root}/audio-files
